version: "3"
services:
  webapp:
    build: .
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
    ports:
      - "8080:8080"
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "Password"
      MYSQL_DATABASE: "nicola_db"
    ports:
      - "3306:3306"
    volumes:
      - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume: